#!/usr/bin/env python3
"""Collect shipped Rust dependency license texts from the locked Cargo graph.

Uses local registry sources only. Includes build/test and target-specific packages
conservatively; this is an inventory, not a binary-link or legal-compliance audit.
Run after fetching dependencies; use --check to detect stale generated notices.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "licenses" / "RUST_DEPENDENCIES.md"
PREFIXES = ("license", "licence", "copying", "copyright", "notice")


def render():
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--offline", "--format-version", "1"],
        cwd=ROOT, text=True,
    ))
    packages = sorted((p for p in metadata["packages"] if p["source"] is not None),
                      key=lambda p: (p["name"], p["version"]))
    digest = hashlib.sha256((ROOT / "Cargo.lock").read_bytes()).hexdigest()
    sections = [
        "# Rust dependency licenses\n\n",
        "Generated by `python3 scripts/generate_license_notices.py`. Do not edit manually.\n\n",
        f"Cargo.lock SHA-256: `{digest}`\n\n",
        "Includes runtime, build, test, and platform-specific packages in the resolved graph.\n",
        "License expressions are upstream declarations, not a choice of alternatives.\n",
        "Consult upstream sources for embedded third-party material not covered by\n",
        "top-level license files.\n\n",
        "| Package | Version | Declared license |\n| --- | --- | --- |\n",
    ]
    for package in packages:
        sections.append(f"| {package['name']} | {package['version']} | {package['license'] or 'See license file'} |\n")
    for package in packages:
        directory = Path(package["manifest_path"]).parent
        files = set()
        for path in directory.iterdir():
            if path.name.lower().startswith(PREFIXES):
                if path.is_file():
                    files.add(path)
                elif path.is_dir():
                    files.update(child for child in path.rglob("*") if child.is_file())
        if package.get("license_file"):
            files.add(directory / package["license_file"])
        if not files:
            directory = ROOT / "licenses" / "upstream" / f"{package['name']}-{package['version']}"
            if directory.is_dir():
                files.update(path for path in directory.iterdir() if path.is_file())
            if not files:
                raise RuntimeError(f"No shipped or recorded upstream license text found: {package['name']} {package['version']}")
        sections.append(f"\n## {package['name']} {package['version']}\n\n")
        sections.append(f"Declared license: `{package['license'] or 'See below'}`\n\n")
        sections.append(f"Source: https://crates.io/crates/{package['name']}/{package['version']}\n\n")
        if package.get("repository"):
            sections.append(f"Upstream: {package['repository']}\n\n")
        for path in sorted(files):
            content = path.read_text(encoding="utf-8")
            sections.append(f"### {path.relative_to(directory)}\n\n~~~~text\n{content}")
            if not content.endswith("\n"):
                sections.append("\n")
            sections.append("~~~~\n")
    return "".join(sections), len(packages)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content, count = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Dependency notices are missing or stale; regenerate them.")
        print(f"Dependency notices match the locked graph ({count} packages).")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)} ({count} packages).")


if __name__ == "__main__":
    main()
